package net.jetensky.upce.twa;// Generated by Selenium IDE

import net.jetensky.upce.twa.pages.DashBoardPage;
import net.jetensky.upce.twa.pages.LoginInPage;
import net.jetensky.upce.twa.pages.WelcomePage;
import net.jetensky.upce.twa.testframework.pages.DashboardPage;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;


public class ToggleChildTest extends AbstractUITest {

    LoginInPage loginInPage;
    WelcomePage welcomePage;
    DashBoardPage dashBoardPage;

    @Before
    public void before() {
        dashBoardPage = new DashBoardPage(driver);
        loginInPage = new LoginInPage(driver, dashBoardPage);
        welcomePage = new WelcomePage(driver, loginInPage);
    }

    @Test
    public void testSignIn() {
        welcomePage
        .visit()
            .clickLogin()
            .typeEmail("pavel.jetensky@seznam.cz")
            .typePassword("stromlze")
        .submit()
        .assertPresence();

    }




}